architecture: replication
auth:
  rootPassword: root-pass
  database: app-db
  username: user
  password: pass

volumePermissions:
  enabled: false

primary:
  persistence:
    enabled: true
    storageClass: csi-disk
    accessModes: ["ReadWriteOnce"]

secondary:
  replicaCount: 1 # plus primary = 2 replicas in total
  persistence:
    storageClass: csi-disk
    accessModes: ["ReadWriteOnce"]

global:
  security:
    allowInsecureImages: True
image:
  registry: docker.io
  tag: 8.0.30
  repository: bitnamilegacy/mysql
